NGIN: NGIN::IO::File::SetupFunctionPointers
SetupFunctionPointers()
template<typename StoragePolicy = TypeErasure::DynamicStoragePolicy> template<typename T > void NGIN::IO::File< StoragePolicy >::SetupFunctionPointers () inline private
Sets up function pointers based on the type T.
Template Parameters
T The type to set up function pointers for.
References NGIN::IO::File< StoragePolicy >::Close(), NGIN::IO::File< StoragePolicy >::close, NGIN::IO::File< StoragePolicy >::Open(), NGIN::IO::File< StoragePolicy >::open, NGIN::IO::File< StoragePolicy >::Read(), NGIN::IO::File< StoragePolicy >::read, NGIN::IO::File< StoragePolicy >::Seek(), NGIN::IO::File< StoragePolicy >::seek, NGIN::IO::File< StoragePolicy >::Write(), and NGIN::IO::File< StoragePolicy >::write.