name: CMake and Documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  CONFIG: x64-release

jobs:
  build_documentation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Doxygen
      run: sudo apt-get install doxygen

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: 1.3.204.0
        cache: true

    - name: Setup CMake, Ninja, and GCC
      uses: lukka/get-cmake@latest
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DNGIN_BUILD_TESTS=OFF -DBUILD_DOCUMENTATION=ON
      
    - name: Build Documentation
      run: cmake --build ${{github.workspace}}/build --preset buildDocs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{github.workspace}}/build/x64-release-final/DOCS/html
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: 1.3.204.0
        cache: true

    - name: Setup CMake, Ninja, and GCC
      uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DNGIN_BUILD_TESTS=ON -DBUILD_DOCUMENTATION=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.CONFIG}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

