# This is a basic workflow to help you get started with Actions

name: Documentation

# Controls when the action will run. 
on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_documentation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: ssciwr/doxygen-install@v1
      with:
        version: "1.9.7"

    - name: Setup graphviz
      run: sudo apt-get -y install graphviz

    - name: Setup CMake, Ninja, and GCC
      uses: lukka/get-cmake@latest

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: latest
        cache: true
        quiet: true
      
    - name: Configure CMake
      run: cmake -S . --preset x64-release-final

      
    - name: Build Documentation
      run: cmake --build --preset buildDocs
      
    - name: Pages Deployment
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{github.workspace}}/build/x64-release-final/DOCS/html
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true